# Generated by Django 2.1.7 on 2020-07-16 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tapi', '0002_papi'),
    ]

    operations = [
        migrations.CreateModel(
            name='Iapi',
            fields=[
                ('ITEMID', models.IntegerField(default='', primary_key=True, serialize=False, verbose_name='ITEMID')),
                ('name', models.CharField(default='', max_length=70)),
                ('description', models.CharField(default='', max_length=70)),
                ('unit', models.CharField(default='', max_length=70)),
                ('opstock', models.DecimalField(decimal_places=4, default='', max_digits=12)),
                ('clstock', models.DecimalField(decimal_places=4, default='', max_digits=12)),
                ('rate', models.DecimalField(decimal_places=4, default='', max_digits=12)),
                ('purrate', models.DecimalField(decimal_places=4, default='', max_digits=12)),
                ('mrp', models.DecimalField(decimal_places=4, default='', max_digits=12)),
                ('gstPER', models.DecimalField(decimal_places=4, default='', max_digits=12)),
                ('slcode', models.IntegerField(default='')),
                ('purcode', models.IntegerField(default='')),
            ],
        ),
    ]
