# Generated by Django 2.1.7 on 2020-07-17 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tapi', '0003_iapi'),
    ]

    operations = [
        migrations.CreateModel(
            name='Smainapi',
            fields=[
                ('INV1REFNO', models.CharField(default='', max_length=70, primary_key=True, serialize=False, verbose_name='INV1REFNO')),
                ('INV1DATE', models.DateField()),
                ('INV1TYPE', models.CharField(default='', max_length=70)),
                ('NV1INVNO', models.CharField(default='', max_length=70)),
                ('INV1INVDT', models.DateField()),
                ('INV1PAYTM', models.CharField(default='', max_length=70)),
                ('INV1DESP', models.CharField(default='', max_length=70)),
                ('INV1PKGS', models.CharField(default='', max_length=70)),
                ('INV1BROKCD', models.IntegerField(default='')),
                ('INV1CHLNO', models.CharField(default='', max_length=70)),
                ('INV1CHLDT', models.DateField()),
                ('INV1AMT', models.DecimalField(decimal_places=4, max_digits=12)),
                ('INV1NET', models.DecimalField(decimal_places=4, max_digits=12)),
                ('INV1DISPER', models.DecimalField(decimal_places=4, max_digits=12)),
                ('INV1DISAMT', models.DecimalField(decimal_places=4, max_digits=12)),
                ('INV1GSTPER', models.DecimalField(decimal_places=4, max_digits=12)),
                ('INV1GSTAMT', models.DecimalField(decimal_places=4, max_digits=12)),
                ('INV1OTH', models.DecimalField(decimal_places=4, max_digits=12)),
                ('INV1ROUND', models.DecimalField(decimal_places=4, max_digits=12)),
                ('INV1BRAMT', models.DecimalField(decimal_places=4, max_digits=12)),
                ('INV1DONE', models.BooleanField()),
                ('INV1UDT', models.DateField()),
                ('INV1EDT', models.DateField()),
                ('INV1REMARK', models.CharField(max_length=60)),
                ('INV1PRTYCD', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tapi.Papi')),
            ],
        ),
    ]
