# Generated by Django 2.1.7 on 2020-07-17 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tapi', '0004_smainapi'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stranapi',
            fields=[
                ('INV1REFNO', models.CharField(default='', max_length=5, primary_key=True, serialize=False, verbose_name='INV1REFNO')),
                ('INV2DATE', models.DateField()),
                ('INV2TYPE', models.CharField(default='', max_length=70)),
                ('INV2UNIT', models.CharField(default='', max_length=70)),
                ('INV2BATCH', models.CharField(default='', max_length=70)),
                ('INV2QNT', models.DecimalField(decimal_places=4, max_digits=12)),
                ('INV2RATE', models.DecimalField(decimal_places=4, max_digits=12)),
                ('INV2AMT', models.DecimalField(decimal_places=4, max_digits=12)),
                ('INV2GSTPER', models.DecimalField(decimal_places=4, max_digits=12)),
                ('INV2GSTAMT', models.DecimalField(decimal_places=4, max_digits=12)),
                ('INV2PRODCD', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tapi.Iapi')),
                ('INV2PRTYCD', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tapi.Papi')),
            ],
        ),
    ]
