# Generated by Django 2.1.7 on 2020-07-20 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tapi', '0005_stranapi'),
    ]

    operations = [
        migrations.AddField(
            model_name='stranapi',
            name='slug',
            field=models.SlugField(default='', max_length=5),
        ),
    ]
