# Generated by Django 2.1.7 on 2020-07-21 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tapi', '0006_stranapi_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stranapi',
            name='slug',
        ),
    ]
