# Generated by Django 2.1.7 on 2020-07-22 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tapi', '0007_remove_stranapi_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ledgerapi',
            fields=[
                ('TRNNO', models.CharField(default='', max_length=10, primary_key=True, serialize=False, verbose_name='TRNNO')),
                ('TRNDATE', models.DateField()),
                ('TRNTYPE', models.CharField(default='', max_length=70)),
                ('TRNCODE', models.IntegerField()),
                ('TRNAMT', models.DecimalField(decimal_places=4, max_digits=12)),
                ('AMTTYPE', models.CharField(default='', max_length=70)),
                ('TRNNER', models.CharField(default='', max_length=70)),
            ],
        ),
    ]
